#!/bin/bash

BRANCH = "$(git rev-parse --abbrev-ref HEAD)"
read -p 'Enter Commit message:' commit_message
git add . && git commit -m "$commit_messge"
if [[ "$BRANCH" == "master" || "$BRANCH" == "main"]]
then
	git push;
	exit 1;
else
	read -p 'Enter Branch name: ' branch_name
	git push -u origin "$branch_name";
fi
